version: '3'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
volumes:
  db_data:
  app_data:
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
    - back
  app:
    image: piwik:fpm
    links:
      - db
    volumes:
      - app_data:/var/www/html
    networks:
    - back
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - app_data:/var/www/html
    links:
      - app
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOST
    networks:
    - back
    - lb_web
  cron:
    image: piwik:fpm
    links:
      - db
    volumes:
      - app_data:/var/www/html
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
    networks:
    - back
